apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  # modify replicas according to your case
  replicas: 7
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: stacksimplify/kube-helloworld:1.0.0
        ports:
        - name: web
          containerPort:  80
          protocol: TCP